language: python
python:
  - "3.5"
  - "3.6"

install:
  - python setup.py install
  - pip install coveralls
  - pip install pytest-cov

before_script:
  - cd test

script:
  - pytest --cov=pyggi
  - coveralls
